version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - "9003"
    ports:
      - 80:80      
    networks:
      - techjourney
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"  
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: techjourney
    volumes:
      - mysql-db-data:/var/lib/mysql 
    networks:
      - techjourney

networks:
  techjourney:

volumes: 
  mysql-db-data: